spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bean_api
    username: root
    password: sa423429
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB

server:
  address: 0.0.0.0
  port: 8100
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000

dubbo:
  application:
    name: beanapi-backend
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848
