server:
  port: 8090
  servlet:
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000

spring:
  application:
    name: beanapi-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: beanapi_backend_route
          uri: lb://beanapi-backend
          predicates:
          - Path=/api/**
  redis:
    port: 6379
    database: 2
    host: localhost
    timeout: 5000

dubbo:
  application:
    name: beanapi-gateway
  protocol:
    name: dubbo
    port: -1
  registry:
#    id: nacos-registry
    address: nacos://localhost:8848
