server:
  port: 8123
  servlet:
    context-path: /api/interface

spring:
  application:
    name: beanapi-interface
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848


beanapi:
  client:
    access-key: sami
    secret-key: 12345678
